language: python

env:
  - TWISTED=Twisted==10.1
  - TWISTED=Twisted==10.2
  - TWISTED=Twisted==11.0
  - TWISTED=Twisted==11.1
  - TWISTED=Twisted==12.0
  - TWISTED=Twisted==12.1
  - TWISTED=Twisted==12.2
  - TWISTED=Twisted==12.3
  - TWISTED=svn+svn://svn.twistedmatrix.com/svn/Twisted/trunk

python:
  - 2.5
  - 2.6
  - 2.7
  - pypy

install:
  - pip install -q $TWISTED pytest -r requirements.txt --use-mirrors

script: py.test txsocksx
